### ISSUE TITLE
Relicensing as MIT

### ISSUE THREAD

**Issue by agkozak** [agkozak/agkozak-zsh-theme#4]
I would like to relicense the next version of `agkozak-zsh-theme` as MIT for better compatibility with other software projects. @xuanduc987 and @jupl, are you willing to license your contributions as MIT?

**Comment by xuanduc987** [comment]
Of courses 🎆

**Comment by jupl** [comment]
![giphy](https://user-images.githubusercontent.com/2065876/34262260-7c5b1918-e631-11e7-964f-a2ccfb053906.gif)

**Comment by jupl** [comment]
And for legal reasons if a GIF is not accepted, then yes.

**Comment by agkozak** [comment]
Thank you, gentlemen!
