### ISSUE TITLE
Option to Disable Multi-Line Mode

### ISSUE THREAD

**Issue by joeleisner** [agkozak/agkozak-zsh-theme#6]
I noticed in the most recent update to this theme that the default configuration has switched to a multi-line prompt due to issues with ZSH 5.5 - Is there any way to set a variable to revert it back to a single line prompt?

I noticed in a commit not that long ago that there was, at least initially, a variable called $AGKOZAK_MULTILINE that would allow you toggle between the modes, but I'm unable to find this variable in the most recent updates.

Let me know! Thanks again for all the hard work.

**Comment by agkozak** [comment]
The simple answer is yes -- give me a couple of hours and I'll provide an option for restoring the legacy, one-line prompt, with the proviso that it may not always work perfectly in ZSH 5.5 and later.

ZSH 5.5 [changes](https://github.com/zsh-users/zsh/commit/d8d9fee137a5aa2cf9bf8314b06895bfc2a05518) how the shell calculates cursor position when the prompt has wrapped. [Apparently there are use cases](http://www.zsh.org/mla/workers/2018/msg00091.html) that I have not run across myself that argue for overhauling this whole aspect of ZSH; what I do know is that in the rare cases that I'm in a directory with an unusually long name and my terminal is rather narrow, when the prompt wraps, the cursor lands on top of the prompt, causing all sorts of irritation. I've spent many hours trying to fix this problem, only to find that I actually don't mind a two-line prompt, which avoids this whole problem entirely.

I'll let you know when I've finished putting the single-line option back into the prompt.

**Comment by agkozak** [comment]
All right, the single-line prompt is an option again; just put

    AGKOZAK_MULTILINE=0

before you source the theme in `.zshrc`.

Thanks again for your feedback!

**Comment by joeleisner** [comment]
Thanks for the quick turn around; Much appreciated!

I definitely understand the choice to switch the theme to a multi-line prompt with the issues surrounding ZSH 5.5, but I have yet to run into those issues as of right now and I much prefer the single-line style.

Once again, thanks for the hard work; This is hands-down the best ZSH theme I've used to date!

**Comment by agkozak** [comment]
You're very kind.
